VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Sheet1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
Sub WallStreetStrock():

'Set Variables
Dim i As Double
Dim j As Double
Dim total As Double
Dim ticker As String
Dim lastrow As Long

'Loop Through Worksheets
For Each ws In Worksheets

'Add Header Name New Columns
ws.Range("I1").Value = "Ticker"
ws.Range("J1").Value = "Total Stock Value"

'Set Total
total = 0
j = 2

'Determine the last Row
lastrow = ws.Cells(Rows.Count, 1).End(xlUp).Row

'Loop Through Each Year of Stock Data and Grab the Total Amount
For i = 2 To lastrow
    If ws.Range("A" & i + 1).Value = ws.Range("A" & i).Value Then
        total = total + ws.Range("G" & i).Value

    Else
       'Grab Ticker when it changes
        ticker = ws.Range("A" & i).Value
        'Insert Grabbed Ticker, and Total Volume
        ws.Range("I" & j).Value = ticker
        ws.Range("J" & j).Value = total + ws.Range("G" & i).Value

   'Add a New Row Next Ticker and Reset Total
        j = j + 1
        total = 0
    End If

Next i
Next ws
End Sub
